---
- name: Install virtualenv
  ansible.builtin.shell: pip3 install virtualenv
  
- name: Creating environment
  become_user: "{{ rmq_user }}"
  ansible.builtin.shell: "python3 -m venv {{ rmq_consumer_dir }}/venv"
  args:
    creates: "{{ rmq_consumer_dir }}/venv"
    executable: /bin/bash

- name: Permissions
  ansible.builtin.shell: "chown -R {{ rmq_user }}:{{ rmq_group }} {{ rmq_consumer_dir }}/venv"

- name: Activation and installation
  ansible.builtin.shell:
      cmd: "{{ item }}"
      chdir: "{{ rmq_consumer_dir }}/consumer"
  with_items:
    - ". ../venv/bin/activate && pip install -e . && pip install -r requirements.txt"

- name: Creating configuration
  template:
    src: "{{ rmq_config_file }}"
    dest: "{{ rmq_consumer_dir }}/consumer/configuration/envs/{{ rmq_config_app_env }}_config.yml"
    owner: "{{ rmq_user }}"
    group: "{{ rmq_group }}"
    mode: '0644'
