---
- name: Install dependencies on Debian
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python3
    - python3-pip    
    - python3-dev
  when: ansible_distribution == 'Debian'

- name: Install dependencies on Red Hat
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python3
    - python3-pip    
    - python3-devel
    - python2-dnf
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

- import_tasks: 'user.yml'

- name: Set permissions
  ansible.builtin.command: "{{ item }}"
  with_items:
    - chown -R {{ rmq_user }}:{{ rmq_group }} .
  args:
    chdir: "{{ rmq_consumer_dir }}"

- name: Git checkout
  become_user: "{{ rmq_user }}"
  ansible.builtin.git:
    repo: 'https://github.com/abrararshad/rmq-consumer.git'
    dest: "{{ rmq_consumer_dir }}/consumer"
    version: master
    force: yes

- import_tasks: 'configure.yml'